### PR TITLE
docs(README): add instructions for typescript support

### PR DESCRIPTION
**Pull request by Weffe**

### CODE REVIEW

**Comment by lirantal** [comment]
@Weffe in this README I don't think the typescript "version" is adding any value/different than the rest of the README... ?

**Comment by Weffe** [comment]
Yeah, the TypeScript Usage section is kind of a repeat that just exposes the usage of the extra types `SetVersionByQueryParamOptions` and `CustomParsingFunction` on line 172 and 185. If you want to remove the redundancy then the TypeScript Usage can be simplified to this: 

```ts
import * as express from 'express';
import * as versionRequest from 'express-version-request';

const app = express();
// Set request version statically
app.use(versionRequest.setVersion('1.2.3'));
// ... more versionRequest calls ...
```

**Comment by lirantal** [comment]
Still very much looks redundant... ?
I think it makes sense to add the TypeScript section to the README to hint users that types are supported.

**Comment by Weffe** [comment]
Fair enough. I'll remove the usage section since it's redundant but still leave installing types for this package in the README. How does that sound?

**Comment by lirantal** [comment]
Yep, that makes sense. Thanks!

**Comment by Weffe** [comment]
Everything is good to go!

**Pull request merged**
